---
version: '3.8'

x-roach: &roach
  image: 'docker.io/cockroachdb/cockroach:v20.2.3'
  command: start --insecure --join roach1,roach2,roach3

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_URL: 'postgres://iziweb_dev@roach1:26257/iziweb_dev?sslmode=disable'
    ports:
      - '3000:3000'
    volumes:
      - './:/src'

  roach1:
    <<: *roach
    hostname: roach1
    ports:
      - '26257:26257'
      - '18080:8080'
    volumes:
      - 'roach1:/cockroach/cockroach-data'
  roach2:
    <<: *roach
    hostname: roach2
    volumes:
      - 'roach2:/cockroach/cockroach-data'
  roach3:
    <<: *roach
    hostname: roach3
    volumes:
      - 'roach3:/cockroach/cockroach-data'

volumes:
  roach1: {}
  roach2: {}
  roach3: {}
